### ISSUE TITLE
dark mode causing my game to crash?

### ISSUE THREAD

**Issue by KSol72** [zohnannor/dark-mode-gd#2]
the only real indicator to why my geode is crashing is because of this .dll called "Liblocos" or something like that,
 when i search liblocos into my installed mods this is the only thing that comes up, i can send the crashlog if you'd like but i think this is my problem rn

**Comment by zohnannor** [comment]
Honestly I don't even know how liblocos is related to this mod (don't know what that is either), so I suspect that it's not the reason, but anyway, yeah, the logs would be helpful

**Comment by zohnannor** [comment]
feel free to reopen if new info (screenshots, logs) provided

**Comment by KSol72** [comment]
Heres the crash log I get:
[2024-03-30_23-43-27.log](https://github.com/zohnannor/dark-mode-gd/files/14814039/2024-03-30_23-43-27.log)
same text shows up when the game crashes I believe

**Comment by KSol72** [comment]
it seems to always crash after loading into 7 levels or so, never the first time or anything, very strange.
& my game crashes way more than my friends so im just trying to narrow down the problem at this point

This is the list of my installed mods, if you need that.
![Screenshot_2](https://github.com/zohnannor/dark-mode-gd/assets/143913267/59ed58d9-958e-4708-ad35-dc8006188432)

**Comment by zohnannor** [comment]
I don't think this is the problem with Dark Mode I'm afraid.

From the stack trace, I see those mods mentioned:

```
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\geode.node-ids\geode.node-ids.dll + 59580
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\absolllute.megahack\absolllute.megahack.dll + df184
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\acaruso.slope\acaruso.slope.dll + 8e53
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\acaruso.slope\acaruso.slope.dll + 8c7c
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 35780
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 19e08
```

```
x | [v8.0.0-alpha.134] absolllute.megahack
x | [v0.1.6] acaruso.slope
x | [v1.3.6] dankmeme.globed2
x | [v1.8.1] geode.node-ids
```

Try disabling them one by one and then testing if the issue persists. There is also a possibility that two mods might somehow conflict with each other, so you'll have to check for that too (enable only 1, enable only 2, enable both).

**Comment by KSol72** [comment]
Alright will do, thanks for the help :)
