### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by gonkergd** [zohnannor/dark-mode-gd#3]
![image](https://github.com/zohnannor/dark-mode-gd/assets/59105483/9e2eaad1-8cd5-4f0b-8594-a92f49bd5f86)

**Comment by zohnannor** [comment]
what am I supposed to look at

**Comment by gonkergd** [comment]
wait sorry wrong screenshot its a screenshot bug
anyways when u press install here it says checksum error

**Comment by zohnannor** [comment]
I still don't know what the error is exactly (you can edit the posts/comments btw). I assume it's an issue with the mod metadata, so you might just wait for an update (currently waiting for the approval https://github.com/geode-sdk/indexer/issues/1670), that should fix it i think.

**Comment by zohnannor** [comment]
check now

**Comment by gonkergd** [comment]
works, thx
